SOURCE_SITE = "travessa"
BASE_URL = "https://www.travessa.com.br"
BOOKS_PATH = "/livros"
REQUEST_DELAY_SECONDS = 0.35

DEFAULT_MAX_CATEGORIES = 1
DEFAULT_MAX_PAGES_PER_CATEGORY = 1
DEFAULT_MAX_PRODUCTS = 10
